# -*- mode: ruby -*-

# For a complete reference, please see the online documentation at
# https://docs.vagrantup.com.

# Vagrantfile for a single Master + Agent Nodes cluster

# The hostname must be properly configured, or stuff won't work in the UI
# Remember to update /etc/hosts on the dev box to point to the correct IP
#   192.168.33.10    mesos-master
#   192.168.33.11    mesos-agent

Vagrant.require_version ">= 1.8"

Vagrant.configure("2") do |config|

  # Use Ubuntu 16.04; disable automatic box update checking, which is, honestly, a pain.
  config.vm.box = "ubuntu/xenial64"
  config.vm.box_check_update = false

# Uncomment this if you need to see the GUI while booting
# It takes a long time to bring up Ubuntu 16.04.
#  config.vm.provider :virtualbox do |vb|
#    vb.gui = true
#  end

  config.vm.define "master" do |master|
    config.vm.provider "virtualbox" do |vb|
        vb.name = "vagrant-mesos-master"

        # This uses a Vagrant 1.8 new feature to save time and space.
        # Comment it out if using an earlier version (not recommended).
        # See: https://www.vagrantup.com/docs/virtualbox/configuration.html
        vb.linked_clone = true
    end
    master.vm.hostname = "mesos-master"

    # Create a private network, which allows host-only access to the machine
    # using a specific IP and forward the Master port to Host
    #
    master.vm.network "private_network", ip: "192.168.33.10"
    master.vm.network "forwarded_port", guest: 5050, host: 5050


    # Mesos (deb pkg) and its dependencies
    master.vm.provision "Install Mesos", type: "shell" do |s|
      s.path = "install-mesos.sh"
    end

    # Docker
    master.vm.provision "Install Docker", type: "shell" do |s|
      s.path = "install-docker.sh"
    end

    # Launch Mesos Master
    master.vm.provision "Run Master", type: "shell", run: "always" do |s|
        s.path = "run-master.sh"
    end

    # Copy the startup script so it's available when the VM gets rebooted.
    master.vm.provision "file", source: "run-master.sh", destination: "run-master.sh"
  end

  config.vm.define "agent" do |agent|
    agent.vm.hostname = "mesos-agent"

    config.vm.provider "virtualbox" do |vb|
        vb.memory = 1024
        vb.name = "vagrant-mesos-agent"
        vb.linked_clone = true
    end

    # Create a private network, which allows host-only access to the machine
    # using a specific IP and forward the Master port to Host
    #
    agent.vm.network "private_network", ip: "192.168.33.11"
    agent.vm.network "forwarded_port", guest: 5051, host: 5051
    agent.vm.network "forwarded_port", guest: 8080, host: 8080

    # Installs Mesos (deb pkg) and its dependencies):
    agent.vm.provision "Install Mesos", type: "shell" do |s|
      s.path = "install-mesos.sh"
    end

    # Installing Docker
    agent.vm.provision "Install Docker", type: "shell" do |s|
      s.path = "install-docker.sh"
    end

    # Launch Mesos Agent
    agent.vm.provision "Run Agent #1", type: "shell", run: "always" do |s|
        s.path = "run-agent.sh"
    end

    # Copy the startup script so it's available when the VM gets rebooted.
    agent.vm.provision "file", source: "run-agent.sh", destination: "run-agent.sh"
  end
end
