# -*- mode: ruby -*-

# For a complete reference, please see the online documentation at
# https://docs.vagrantup.com.

# Vagrantfile for a single Master + Agent Nodes cluster
# TODO(marco): add a ZK node

# The hostname must be properly configured, or stuff won't work in the UI
# Remember to update /etc/hosts on the dev laptop to point to the correct IP
#   192.168.33.10    mesos-master
#   192.168.33.11    mesos-agent

Vagrant.require_version ">= 1.5"

Vagrant.configure("2") do |config|

  # Use Ubuntu 14.04; disable automatic box update checking.
  config.vm.box = "ubuntu/trusty64"
  config.vm.box_check_update = false

  config.vm.define "master" do |master|
    master.vm.host_name = "mesos-master"

    # Create a private network, which allows host-only access to the machine
    # using a specific IP and forward the Master port to Host
    #
    master.vm.network "private_network", ip: "192.168.33.10"
    master.vm.network "forwarded_port", guest: 5050, host: 5050

    # Installs Mesos (deb pkg) and its dependencies):
    master.vm.provision "Install Mesos", type: "shell" do |s|
      s.path = "install-mesos.sh"
    end

    # Launch Mesos Master
    master.vm.provision "Run Master", type: "shell", run: "always" do |s|
        s.path = "run-master.sh"
    end
  end

  config.vm.define "agent" do |agent|
    agent.vm.host_name = "mesos-agent"

    config.vm.provider "virtualbox" do |vb|
        vb.memory = 1024
    end

    # Create a private network, which allows host-only access to the machine
    # using a specific IP and forward the Master port to Host
    #
    agent.vm.network "private_network", ip: "192.168.33.11"
    agent.vm.network "forwarded_port", guest: 5051, host: 5051
    agent.vm.network "forwarded_port", guest: 8080, host: 8080

    # Installs Mesos (deb pkg) and its dependencies):
    agent.vm.provision "Install Mesos", type: "shell" do |s|
      s.path = "install-mesos.sh"
    end

    # Installing Docker on the Agent only
    agent.vm.provision "Install Docker", type: "shell" do |s|
      s.path = "install-docker.sh"
    end

    # Launch Mesos Agent
    agent.vm.provision "Run Agent #1", type: "shell", run: "always" do |s|
        s.path = "run-agent.sh"
    end
  end
end
